version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-npm
    environment:
      MYSQL_ROOT_PASSWORD: oumayma
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres-npm
    environment:
      POSTGRES_PASSWORD: oumayma
    ports:
      - "5439:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo-npm
    ports:
      - "28019:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mysql-data:
  postgres-data:
  mongo-data:
